### ISSUE TITLE
All my opening moves are labeled as "Invalid move"  :-(

### ISSUE THREAD

**Issue by rickhg12hs** [benwilliamgraham/durfeechess#2]
I tried to play by moving the pawns or the knights (left click, hold, drag, release), but it didn't work and the message was "Invalid move".

Google Chrome Version 103.0.5060.114 (Official Build) (64-bit) on Wayland Gnome on Fedora 35.

**Comment by benwilliamgraham** [comment]
As of now it will always return invalid move, but hopefully soon it'll be fully-functioning
